In [116]:
import requests
import pandas as pd
from datetime import datetime, timedelta

In [120]:
iata = "ALA"
key = "4c9daccbaa0ab0dc63923014205e07c3"
offset = 0
df = pd.DataFrame()
anal_columns = [
    'flight_date', 
    'flight_status', 
    'departure.airport', 
    'departure.terminal', 
    'departure.scheduled', 
    'departure.actual',
    'departure.delay',
    'arrival.airport', 
    'arrival.baggage',
    'arrival.scheduled',
    'flight.codeshared.airline_name',
]
prev_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')

print(f"Yesterday was: {prev_date}")

def download_json(url):
    response = requests.get(url)
    response.raise_for_status()  # Raises HTTPError for 4xx or 5xx responses
    return response.json()

while True:
    url = f"http://api.aviationstack.com/v1/flights?access_key={key}&dep_iata={iata}&offset={offset}"
    temp_json = download_json(url)
    df = pd.concat([df, pd.json_normalize(temp_json['data'])])
    pd.json_normalize(data_1['data'])
    print(f"Offset = {offset}")
    if int(temp_json["pagination"]["count"]) < 100:
        break
    else:
        offset += 100
        
def sort_df(date):
    selected_columns = df[anal_columns]
    filtered_df = selected_columns[df['flight_date'] == date]
    sorted_df = filtered_df.sort_values(by='departure.scheduled', ascending=True)
    return sorted_df

sort_df(prev_date)

Yesterday was: 2024-03-25
Offset = 0
Offset = 100
Offset = 200
Offset = 300

,flight_date,flight_status,departure.airport,departure.terminal,departure.scheduled,departure.actual,departure.delay,arrival.airport,arrival.baggage,arrival.scheduled,flight.codeshared.airline_name
1,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,air astana
0,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,NaN
99,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,air astana
50,2024-03-25,landed,Almaty,None,2024-03-25T00:25:00+00:00,2024-03-25T00:31:00+00:00,7.0,Suvarnabhumi International,None,2024-03-25T08:55:00+00:00,NaN
49,2024-03-25,landed,Almaty,None,2024-03-25T00:25:00+00:00,2024-03-25T00:31:00+00:00,7.0,Suvarnabhumi International,None,2024-03-25T08:55:00+00:00,air astana
...,...,...,...,...,...,...,...,...,...,...,...
61,2024-03-25,landed,Almaty,None,2024-03-25T23:20:00+00:00,2024-03-25T23:38:00+00:00,19.0,Nursultan Nazarbayev International Airport,None,2024-03-26T01:05:00+00:00,NaN
87,2024-03-25,active,Almaty,None,2024-03-25T23:30:00+00:00,2024-03-25T23:36:00+00:00,6.0,Atyrau International,None,2024-03-26T02:50:00+00:00,NaN
91,2024-03-25,active,Almaty,None,2024-03-25T23:30:00+00:00,2024-03-25T23:36:00+00:00,6.0,Atyrau International,None,2024-03-26T02:50:00+00:00,air astana
20,2024-03-25,scheduled,Almaty,None,2024-03-25T23:45:00+00:00,None,NaN,Krasnojarsk,None,2024-03-26T04:30:00+00:00,NaN
19,2024-03-25,landed,Almaty,None,2024-03-25T23:45:00+00:00,2024-03-26T00:04:00+00:00,20.0,Krasnojarsk,None,2024-03-26T04:30:00+00:00,NaN

In [128]:
bucket_name = "de-project-flight-analyzer"
iata = "ALA"
url_base = f"http://api.aviationstack.com/v1/flights?access_key=4c9daccbaa0ab0dc63923014205e07c3&dep_iata={iata}"
offset = 0
json_data = []

def download_data(url):
    response = requests.get(url)
    response.raise_for_status()  # Raise an HTTPError for bad responses
    return response.json()

while True:
    url = f"{url_base}&offset={offset}"
    temp_json = download_data(url)
    json_data.extend(temp_json["data"])
    if int(temp_json["pagination"]["count"]) < 100:
        break
    else:
        offset += 100

In [139]:
prev_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
df = pd.json_normalize(json_data)
df

,flight_date,flight_status,aircraft,live,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,...,live.direction,live.speed_horizontal,live.speed_vertical,live.is_ground,flight.codeshared.airline_name,flight.codeshared.airline_iata,flight.codeshared.airline_icao,flight.codeshared.flight_number,flight.codeshared.flight_iata,flight.codeshared.flight_icao
0,2024-03-26,scheduled,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-03-26,scheduled,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-03-26,scheduled,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-03-26,landed,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-03-26,landed,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,2024-03-25,landed,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,2024-03-25,active,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,2024-03-25,unknown,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,2024-03-25,landed,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,2024-03-25,active,NaN,NaN,Almaty,Asia/Almaty,ALA,UAAA,None,GT1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
sort_df(prev_date)

,flight_date,flight_status,departure.airport,departure.terminal,departure.scheduled,departure.actual,departure.delay,arrival.airport,arrival.baggage,arrival.scheduled,flight.codeshared.airline_name
210,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,air astana
209,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,NaN
208,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,air astana
159,2024-03-25,landed,Almaty,None,2024-03-25T00:25:00+00:00,2024-03-25T00:31:00+00:00,7.0,Suvarnabhumi International,None,2024-03-25T08:55:00+00:00,NaN
158,2024-03-25,landed,Almaty,None,2024-03-25T00:25:00+00:00,2024-03-25T00:31:00+00:00,7.0,Suvarnabhumi International,None,2024-03-25T08:55:00+00:00,air astana
...,...,...,...,...,...,...,...,...,...,...,...
270,2024-03-25,landed,Almaty,None,2024-03-25T23:20:00+00:00,2024-03-25T23:38:00+00:00,19.0,Nursultan Nazarbayev International Airport,None,2024-03-26T01:05:00+00:00,NaN
196,2024-03-25,active,Almaty,None,2024-03-25T23:30:00+00:00,2024-03-25T23:36:00+00:00,6.0,Atyrau International,None,2024-03-26T02:50:00+00:00,NaN
200,2024-03-25,active,Almaty,None,2024-03-25T23:30:00+00:00,2024-03-25T23:36:00+00:00,6.0,Atyrau International,None,2024-03-26T02:50:00+00:00,air astana
229,2024-03-25,scheduled,Almaty,None,2024-03-25T23:45:00+00:00,None,NaN,Krasnojarsk,None,2024-03-26T04:30:00+00:00,NaN
228,2024-03-25,landed,Almaty,None,2024-03-25T23:45:00+00:00,2024-03-26T00:04:00+00:00,20.0,Krasnojarsk,None,2024-03-26T04:30:00+00:00,NaN

In [143]:
df = df.drop_duplicates(subset=["arrival.airport", "departure.scheduled"], keep='first')
sort_df(prev_date)

,flight_date,flight_status,departure.airport,departure.terminal,departure.scheduled,departure.actual,departure.delay,arrival.airport,arrival.baggage,arrival.scheduled,flight.codeshared.airline_name
208,2024-03-25,landed,Almaty,None,2024-03-25T00:15:00+00:00,2024-03-25T00:27:00+00:00,12.0,Seoul (Incheon),22,2024-03-25T09:55:00+00:00,air astana
158,2024-03-25,landed,Almaty,None,2024-03-25T00:25:00+00:00,2024-03-25T00:31:00+00:00,7.0,Suvarnabhumi International,None,2024-03-25T08:55:00+00:00,air astana
207,2024-03-25,landed,Almaty,None,2024-03-25T00:30:00+00:00,2024-03-25T00:48:00+00:00,19.0,Phuket International,None,2024-03-25T09:30:00+00:00,NaN
252,2024-03-25,landed,Almaty,None,2024-03-25T01:10:00+00:00,2024-03-25T01:48:00+00:00,38.0,Nursultan Nazarbayev International Airport,None,2024-03-25T03:10:00+00:00,lufthansa
201,2024-03-25,landed,Almaty,None,2024-03-25T02:00:00+00:00,2024-03-25T02:04:00+00:00,4.0,Heydar Aliyev International (Bina International),None,2024-03-25T05:00:00+00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...
306,2024-03-25,landed,Almaty,None,2024-03-25T22:20:00+00:00,2024-03-25T22:28:00+00:00,8.0,Sheremetyevo International,1,2024-03-26T01:20:00+00:00,NaN
271,2024-03-25,landed,Almaty,None,2024-03-25T23:05:00+00:00,2024-03-25T23:22:00+00:00,17.0,Nursultan Nazarbayev International Airport,None,2024-03-26T00:50:00+00:00,NaN
270,2024-03-25,landed,Almaty,None,2024-03-25T23:20:00+00:00,2024-03-25T23:38:00+00:00,19.0,Nursultan Nazarbayev International Airport,None,2024-03-26T01:05:00+00:00,NaN
196,2024-03-25,active,Almaty,None,2024-03-25T23:30:00+00:00,2024-03-25T23:36:00+00:00,6.0,Atyrau International,None,2024-03-26T02:50:00+00:00,NaN
228,2024-03-25,landed,Almaty,None,2024-03-25T23:45:00+00:00,2024-03-26T00:04:00+00:00,20.0,Krasnojarsk,None,2024-03-26T04:30:00+00:00,NaN